
name: Deploy to GoDaddy Hosting

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v2

- name: Deploy to GoDaddy
uses: SamKirkland/FTP-Deploy-Action@4.0.0
with:
ftp-server: ftp://yourftpserver.com/your/path
ftp-username: ${{ secrets.FTP_USERNAME }}
ftp-password: ${{ secrets.FTP_PASSWORD }}
```
